import { Inter } from "next/font/google";
import "./globals.css";
import ClientProvider from "@/components/Clientprovider";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Recipe Finder",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <link rel="icon" href="/favicon.ico" />
      </head>
      <body className={inter.className}>
        <ClientProvider>
          {children}
        </ClientProvider>
      </body>
    </html>
  );
}
